services:
  postgres:
    container_name: sharpner_postgres_container
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "35432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: sharpner_pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "30080:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
